// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bibhujhycaqmovtqjzha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpYmh1amh5Y2FxbW92dHFqemhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDAzMTIsImV4cCI6MjA2NTMxNjMxMn0.aFR59rzVCxxotmPxaywNFuPQHcSqAzhfkQQrGqRbnIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);